imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
            longblob: text

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# JquerySlider Configuration

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
ihqs_contact:
    contact:
        form:
            type:               ihqs_contact_contact
            handler:            ihqs_contact.contact.form.handler.default
            name:               ihqs_contact_contact_form
            validation_groups:  [Contact]
    form: ~                                 # (optional) class managing the contact form
    model: ~                                # (optional) class managing the model
    connectors:                             # the list of "listeners" (or connectors here)
        email:                              # connecting the email listener
            recipients: lorenzo@espace-couture-sittler.fr    # giving him the recipient(s) email(s)
        database:                           # connecting the database listener
            db_driver: orm                  # giving him the database driver
        file: ~    
        
gregwar_image: ~

eyeswebcrea_catalogue:
    theme: Default
    id_catalogue: 1
    keywork_categorie: 1
    keywork_produit: 2
    
eyeswebcrea_referencement:
  rubriqueId: 41
  article_manager: spip_acces_content.article_manager
  
eyeswebcrea_alias_content_viewer:
    article_manager: spip_acces_content.article_manager
    rubrique_manager: ~
    
avalanche_sitemap:
    base_url: "http://www.espace-couture-sittler.fr/"

    
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: test_database
    document_managers:
        default:
            mappings:
            # other bundles mapping and etc.
                AvalancheSitemapBundle:
                    type: yml
                    prefix: Avalanche\Bundle\SitemapBundle\Sitemap
                    
google:
    analytics:
        trackers:
            default:
                name:      trackerespacecouturesittlerfr
                accountId: UA-30929876-1
                domain:    .espace-couture-sittler.fr
                trackPageLoadTime: true
